=== montesmites/ekonomi/src/main/resources/xsd/report-definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="se/montesmites/ekonomi/report-definition"
           elementFormDefault="qualified"
           xmlns="se/montesmites/ekonomi/report-definition"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="definition">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="report"/>
                <xs:element ref="section" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="account-group" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="report">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="section" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="section-ref" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="description" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="section">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"/>
                <xs:sequence>
                    <xs:element ref="account-group" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="account-group-ref" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="section-ref" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="section" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:group ref="section-decorator" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="section-decorator">
        <xs:choice>
            <xs:element name="compact-section"/>
            <xs:element name="totalling-section"/>
            <xs:element name="negated-section"/>
            <xs:element name="accumulating-section"/>
        </xs:choice>
    </xs:group>
    <xs:element name="section-ref">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:group ref="section-decorator"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="account-group">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="regex" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="account-group-ref">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== montesmites/ekonomi/src/main/resources/se/montesmites/ekonomi/nikka/nikka-cashflow-report-definition.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns="se/montesmites/ekonomi/report-definition"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="se/montesmites/ekonomi/report-definition ../../../../xsd/report-definition.xsd">
  <report>
    <account-groups>
      <description>Inkomster</description>
      <account-group>
        <description>Löner och arvoden</description>
        <regex>(30\d\d)|(31\d\d)|3950|3990</regex>
      </account-group>
    </account-groups>
    <account-groups>
      <description>Boende</description>
      <account-group>
        <description>Månadsavgift m.m.</description>
        <regex>501\d</regex>
      </account-group>
      <account-group>
        <description>Amortering Fredsgatan 13</description>
        <regex>2353</regex>
      </account-group>
      <account-group>
        <description>Bolån ränta och liknande</description>
        <regex>84[019]\d</regex>
      </account-group>
      <account-group>
        <description>Hemförsäkring</description>
        <regex>5081</regex>
      </account-group>
      <account-group>
        <description>El (förbrukning och nät)</description>
        <regex>502\d</regex>
      </account-group>
      <account-group>
        <description>Mobil, tv, bredband</description>
        <regex>51\d\d</regex>
      </account-group>
      <account-group>
        <description>Boende diverse</description>
        <regex>5060|5[458]\d\d</regex>
      </account-group>
    </account-groups>
    <account-groups>
      <description>Förnödenheter</description>
      <account-group>
        <description>Dagligvaror</description>
        <regex>40\d\d</regex>
      </account-group>
      <account-group>
        <description>Kläder och skor</description>
        <regex>41\d\d</regex>
      </account-group>
      <account-group>
        <description>Kropp och själ</description>
        <regex>42\d\d</regex>
      </account-group>
      <account-group>
        <description>Personförsäkringar</description>
        <regex>43\d\d</regex>
      </account-group>
      <account-group>
        <description>A-kassa, fack, bank</description>
        <regex>4[4-6]\d\d</regex>
      </account-group>
      <account-group>
        <description>Transporter</description>
        <regex>56\d\d</regex>
      </account-group>
      <account-group>
        <description>Övrigt</description>
        <regex>(4[89]|[67]\d)\d\d</regex>
      </account-group>
    </account-groups>
    <subtotal>
      <description>Netto återkommande poster</description>
    </subtotal>
    <account-groups>
      <description>Sparande</description>
      <account-group>
        <description>Buffertsparande</description>
        <regex>149\d</regex>
      </account-group>
      <account-group>
        <description>Räntesparande och liknande</description>
        <regex>134\d</regex>
      </account-group>
      <account-group>
        <description>Aktier och aktiefonder</description>
        <regex>18\d\d</regex>
      </account-group>
    </account-groups>
    <account-groups>
      <description>Jämförelsestörande poster</description>
      <account-group>
        <description>Nettoomsättning utom lön etc.</description>
        <regex>3850|3910|3940</regex>
      </account-group>
      <account-group>
        <description>Kortfristigt netto</description>
        <regex>(1[5-7]|2[4-9])\d\d</regex>
      </account-group>
      <account-group>
        <description>Långfristigt netto</description>
        <regex>(8[56]\d\d)|(10\d\d)|(13[1568]\d)</regex>
      </account-group>
      <account-group>
        <description>Finansiellt netto</description>
        <regex>(83\d\d)|(84[2-8]\d)</regex>
      </account-group>
      <account-group>
        <description>Investeringar och avskrivningar</description>
        <regex>(11\d\d)|(7\d\d\d)</regex>
      </account-group>
      <account-group>
        <description>Extraordinärt netto</description>
        <regex>87\d\d</regex>
      </account-group>
      <account-group>
        <description>Skatt</description>
        <regex>47\d\d</regex>
      </account-group>
    </account-groups>
    <subtotal>
      <description>Förändring kassa och bank</description>
    </subtotal>
    <subtotal>
      <description>Kontrollsumma</description>
      <addenda>
        <account-group>
          <description>Likvida medel</description>
          <regex>19\d\d</regex>
        </account-group>
      </addenda>
    </subtotal>
    <accumulate-account-groups>
      <description>Ack. likvida medel inkl. buffertsparande</description>
      <account-group>
        <description/>
        <regex>1493|19\d\d</regex>
        <negate/>
      </account-group>
    </accumulate-account-groups>
  </report>
</definition>

=== montesmites/ekonomi/src/test/resources/se/montesmites/ekonomi/report/xml/02_subtotal.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns="se/montesmites/ekonomi/report-definition"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="se/montesmites/ekonomi/report-definition ../../../../../../../main/resources/xsd/report-definition.xsd">
  <report>
    <account-groups>
      <description>1111 &amp; 2222</description>
      <account-group>
        <description>1111</description>
        <regex>1111</regex>
      </account-group>
      <account-group>
        <description>2222</description>
        <regex>2222</regex>
      </account-group>
    </account-groups>
    <subtotal>
      <description>subtotal</description>
    </subtotal>
  </report>
</definition>
